IMAGE_SUB_TOPIC = "camera/tracking/image"
TRACK_PUB_TOPIC = "track_rect_pub"
CONFIG_PATH = "/path/to/pysot/models/config.yaml"
MODEL_PATH = "/path/to/pysot/models/models.pth"
TRACK_TYPE = "pysot.tracker.siamrpn_tracker.SiamRPNTracker" #"pysot.tracker.siammask_tracker.SiamMaskTracker | pysot.tracker.siammrpnlt_tracker.SiamRPNLTTracker"