// Generated by gencpp from file ros_kcf/InitRectRequest.msg
// DO NOT EDIT!


#ifndef ROS_KCF_MESSAGE_INITRECTREQUEST_H
#define ROS_KCF_MESSAGE_INITRECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_kcf
{
template <class ContainerAllocator>
struct InitRectRequest_
{
  typedef InitRectRequest_<ContainerAllocator> Type;

  InitRectRequest_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
    }
  InitRectRequest_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
  (void)_alloc;
    }



   typedef int32_t _xmin_type;
  _xmin_type xmin;

   typedef int32_t _ymin_type;
  _ymin_type ymin;

   typedef int32_t _xmax_type;
  _xmax_type xmax;

   typedef int32_t _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::ros_kcf::InitRectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_kcf::InitRectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitRectRequest_

typedef ::ros_kcf::InitRectRequest_<std::allocator<void> > InitRectRequest;

typedef boost::shared_ptr< ::ros_kcf::InitRectRequest > InitRectRequestPtr;
typedef boost::shared_ptr< ::ros_kcf::InitRectRequest const> InitRectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_kcf::InitRectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_kcf::InitRectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_kcf

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_kcf::InitRectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_kcf::InitRectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_kcf::InitRectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7774db90b9f2d2e1375663d80c5c2b9e";
  }

  static const char* value(const ::ros_kcf::InitRectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7774db90b9f2d2e1ULL;
  static const uint64_t static_value2 = 0x375663d80c5c2b9eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_kcf/InitRectRequest";
  }

  static const char* value(const ::ros_kcf::InitRectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 xmin\n\
int32 ymin\n\
int32 xmax\n\
int32 ymax\n\
";
  }

  static const char* value(const ::ros_kcf::InitRectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitRectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_kcf::InitRectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_kcf::InitRectRequest_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_KCF_MESSAGE_INITRECTREQUEST_H
