// Generated by gencpp from file ros_kcf/InitRect.msg
// DO NOT EDIT!


#ifndef ROS_KCF_MESSAGE_INITRECT_H
#define ROS_KCF_MESSAGE_INITRECT_H

#include <ros/service_traits.h>


#include <ros_kcf/InitRectRequest.h>
#include <ros_kcf/InitRectResponse.h>


namespace ros_kcf
{

struct InitRect
{

typedef InitRectRequest Request;
typedef InitRectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitRect
} // namespace ros_kcf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_kcf::InitRect > {
  static const char* value()
  {
    return "7774db90b9f2d2e1375663d80c5c2b9e";
  }

  static const char* value(const ::ros_kcf::InitRect&) { return value(); }
};

template<>
struct DataType< ::ros_kcf::InitRect > {
  static const char* value()
  {
    return "ros_kcf/InitRect";
  }

  static const char* value(const ::ros_kcf::InitRect&) { return value(); }
};


// service_traits::MD5Sum< ::ros_kcf::InitRectRequest> should match 
// service_traits::MD5Sum< ::ros_kcf::InitRect > 
template<>
struct MD5Sum< ::ros_kcf::InitRectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_kcf::InitRect >::value();
  }
  static const char* value(const ::ros_kcf::InitRectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_kcf::InitRectRequest> should match 
// service_traits::DataType< ::ros_kcf::InitRect > 
template<>
struct DataType< ::ros_kcf::InitRectRequest>
{
  static const char* value()
  {
    return DataType< ::ros_kcf::InitRect >::value();
  }
  static const char* value(const ::ros_kcf::InitRectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_kcf::InitRectResponse> should match 
// service_traits::MD5Sum< ::ros_kcf::InitRect > 
template<>
struct MD5Sum< ::ros_kcf::InitRectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_kcf::InitRect >::value();
  }
  static const char* value(const ::ros_kcf::InitRectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_kcf::InitRectResponse> should match 
// service_traits::DataType< ::ros_kcf::InitRect > 
template<>
struct DataType< ::ros_kcf::InitRectResponse>
{
  static const char* value()
  {
    return DataType< ::ros_kcf::InitRect >::value();
  }
  static const char* value(const ::ros_kcf::InitRectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_KCF_MESSAGE_INITRECT_H
